import type { SxProps, Theme } from '@mui/material/styles';

export const pageStyles: Record<string, SxProps<Theme>> = {
  root: {
    minHeight: '100dvh',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    overflowX: 'hidden',
    fontFamily: 'Inter, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    bgcolor: '#edf2ff',
    backgroundImage:
      'radial-gradient(circle at 14% 18%, rgba(61, 112, 223, 0.18), transparent 28%), radial-gradient(circle at 82% 18%, rgba(255, 255, 255, 0.72), transparent 22%), linear-gradient(135deg, #eff4ff 0%, #e7eefc 44%, #f8faff 100%)',
    backgroundSize: '100% 100%, 100% 100%, 100% 100%',
    backgroundPosition: 'center',
  },
  main: {
    flex: 1,
    minHeight: 'auto',
    display: 'flex',
    alignItems: 'stretch',
    justifyContent: 'stretch',
  },
  grid: {
    width: '100%',
    flex: 1,
    maxWidth: 1680,
    mx: 'auto',
    display: 'grid',
    gridTemplateColumns: { xs: '1fr', xl: 'minmax(0, 1.12fr) minmax(360px, 0.88fr)' },
    alignItems: { xs: 'start', xl: 'stretch' },
    gap: { xs: 0, xl: 0 },
  },
  leftPane: {
    order: { xs: 1, xl: 1 },
    minHeight: 'auto',
    p: { xs: 2.5, sm: 3, md: 4, xl: 5.5 },
    bgcolor: 'rgba(246, 249, 255, 0.72)',
    backgroundImage:
      'radial-gradient(circle at 18% 24%, rgba(89, 130, 230, 0.12), transparent 26%), linear-gradient(180deg, rgba(255, 255, 255, 0.54) 0%, rgba(245, 248, 255, 0.78) 100%)',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    overflow: 'visible',
  },
  pill: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    px: 2,
    py: 0.85,
    bgcolor: '#e8efff',
    color: '#3d63cc',
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: '0.09em',
    textTransform: 'uppercase',
  },
  leftTitle: {
    color: '#252f5a',
    fontSize: { xs: 29, sm: 33, md: 40, lg: 46, xl: 50 },
    lineHeight: { xs: 1.08, md: 1.1 },
    fontWeight: 700,
    letterSpacing: '-0.022em',
    fontFamily: '"Poppins", Inter, "Segoe UI", sans-serif',
    textWrap: 'balance',
  },
  featurePanel: {
    mt: { xs: 4, sm: 5, md: 6, xl: 10 },
    px: { xs: 2.5, md: 2.9 },
    py: { xs: 2.5, md: 2.9 },
    width: '100%',
    maxWidth: { xs: '100%', md: 500 },
    borderRadius: 3,
    border: '1px solid #eceffd',
    bgcolor: '#ffffff',
    boxShadow: '0 14px 30px rgba(53, 76, 130, 0.08)',
  },
  featureEyebrow: {
    color: '#2f60d0',
    fontSize: 10.5,
    fontWeight: 700,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
  },
  featureHeading: {
    color: '#2a355f',
    fontSize: { xs: 24, md: 28 },
    lineHeight: 1.2,
    fontWeight: 700,
    letterSpacing: '-0.01em',
  },
  featureDescription: {
    mt: 1.05,
    color: '#677695',
    fontSize: { xs: 14.25, md: 15.25 },
    lineHeight: 1.65,
    maxWidth: '100%',
  },
  featureFadeIn: {
    opacity: 1,
    transform: 'translateY(0px)',
    transition: 'opacity 220ms ease, transform 220ms ease',
  },
  featureFadeOut: {
    opacity: 0,
    transform: 'translateY(5px)',
    transition: 'opacity 170ms ease, transform 170ms ease',
  },
  featureDots: {
    alignItems: 'center',
  },
  featureDotActive: {
    width: 24,
    height: 8,
    borderRadius: 999,
    border: 'none',
    p: 0,
    bgcolor: '#1f5ad3',
    cursor: 'pointer',
    transition: 'all 220ms ease',
  },
  featureDotInactive: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    border: 'none',
    p: 0,
    bgcolor: '#d3d9eb',
    cursor: 'pointer',
    transition: 'all 220ms ease',
    '&:hover': {
      bgcolor: '#aab6d8',
    },
  },
  rightPane: {
    order: { xs: 2, xl: 2 },
    minHeight: 'auto',
    p: { xs: 2.5, sm: 3, md: 4, xl: 5.5 },
    display: 'flex',
    alignItems: { xs: 'stretch', md: 'center' },
    justifyContent: 'center',
    position: 'relative',
    overflow: 'visible',
    background:
      'linear-gradient(180deg, rgba(255, 255, 255, 0.76) 0%, rgba(250, 252, 255, 0.96) 100%)',
  },
  formCard: {
    width: '100%',
    maxWidth: 520,
    position: 'relative',
    overflow: 'hidden',
    borderRadius: 3.2,
    border: '1px solid rgba(225, 232, 248, 0.92)',
    boxShadow: '0 24px 54px rgba(40, 61, 112, 0.10)',
    bgcolor: 'rgba(255, 255, 255, 0.92)',
    mx: 'auto',
    px: { xs: 2.2, sm: 2.7, md: 4.2 },
    py: { xs: 2.5, sm: 3, md: 3.5 },
    backdropFilter: 'blur(8px)',
  },
  formTitle: {
    color: '#252f5a',
    fontFamily: '"Poppins", Inter, "Segoe UI", sans-serif',
    fontSize: { xs: 27, sm: 30, md: 36 },
    lineHeight: 1.15,
    fontWeight: 700,
    letterSpacing: '-0.01em',
    textWrap: 'balance',
  },
  formSubtitle: {
    mt: 0.5,
    color: '#7581a0',
    fontSize: { xs: 14, md: 16 },
    lineHeight: 1.5,
  },
  oauthButton: {
    borderColor: '#dfe4f2',
    color: '#33456d',
    bgcolor: '#fff',
    borderRadius: 2,
    textTransform: 'none',
    fontWeight: 600,
    fontSize: 13.5,
    py: 0.95,
    minHeight: 42,
    '&:hover': {
      borderColor: '#c9d2eb',
      bgcolor: '#f9fbff',
    },
  },
  dividerLine: {
    flex: 1,
    height: 1,
    bgcolor: '#e6eaf4',
  },
  dividerText: {
    color: '#9aa4ba',
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: '0.1em',
    textAlign: 'center',
    whiteSpace: 'nowrap',
  },
  fieldLabel: {
    color: '#606d87',
    fontSize: 10,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
    mb: 0.65,
    display: 'block',
  },
  forgotLink: {
    color: '#5a6d9e',
    fontSize: 11,
    fontWeight: 600,
  },
  rememberLabel: {
    color: '#67738d',
    fontSize: 13,
    lineHeight: 1.4,
  },
  submitButton: {
    minHeight: 48,
    borderRadius: 2.3,
    background: 'linear-gradient(90deg, #0d4ec5 0%, #5f8ef2 100%)',
    boxShadow: '0 8px 22px rgba(46, 95, 205, 0.34)',
    fontFamily: '"Poppins", Inter, "Segoe UI", sans-serif',
    fontSize: 12.5,
    letterSpacing: '0.14em',
    fontWeight: 700,
    '&:hover': {
      background: 'linear-gradient(90deg, #0a45b3 0%, #507fdd 100%)',
    },
  },
  signupPrompt: {
    textAlign: 'center',
    color: '#7a859f',
    fontSize: 13,
    mt: 0.35,
  },
  signupLink: {
    color: '#2d5ac7',
    fontWeight: 600,
  },
};

export const textFieldStyles = {
  '& .MuiOutlinedInput-root': {
    borderRadius: 1,
    bgcolor: '#eef0fb',
    minHeight: 46,
    fontSize: 13.5,
    '& input': {
      px: { xs: 1.15, sm: 1.45 },
      py: 1.2,
    },
    '& fieldset': {
      borderColor: 'transparent',
    },
    '&:hover fieldset': {
      borderColor: '#c7d3f1',
    },
    '&.Mui-focused fieldset': {
      borderColor: '#5a79d3',
    },
  },
  '& .MuiFormHelperText-root': {
    minHeight: 0,
    mt: 0.35,
  },
} as const;
