using IDS.Project.Domain.Enums;
using DomainTaskStatus = IDS.Project.Domain.Enums.TaskStatus;

namespace IDS.Project.Application.DTOs.Tasks;

public sealed record TaskDetailsDto(
    Guid Id,
    string Title,
    string Description,
    string AssignedMemberId,
    string AssignedMemberName,
    string AssignedMemberEmail,
    string CreatedById,
    string CreatedByName,
    Guid TeamId,
    string TeamName,
    TaskSpecialization RequiredSpecialization,
    TaskPriority Priority,
    TaskComplexity Complexity,
    decimal EstimatedEffortHours,
    DateOnly StartDate,
    DateOnly DueDate,
    DomainTaskStatus Status,
    double CalculatedWeight,
    bool IsAcknowledged,
    DateTimeOffset? AcknowledgedAt,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    double ComplexityMultiplier,
    double PriorityMultiplier,
    double AssigneeCapacityPercentageThisWeek,
    TaskReassignmentRequestDto[] ReassignmentRequests,
    TaskStatusTimelineItemDto[] StatusTimeline,
    TaskChangeAuditItemDto[] ChangeAudit,
    TaskCapacityPointDto[] AssigneeCapacity)
{
    public static TaskDetailsDto Empty(Guid id) =>
        new(
            id,
            string.Empty,
            string.Empty,
            string.Empty,
            string.Empty,
            string.Empty,
            string.Empty,
            string.Empty,
            Guid.Empty,
            string.Empty,
            TaskSpecialization.Unknown,
            TaskPriority.Low,
            TaskComplexity.Simple,
            0,
            DateOnly.FromDateTime(DateTime.UtcNow),
            DateOnly.FromDateTime(DateTime.UtcNow),
            DomainTaskStatus.New,
            0,
            false,
            null,
            DateTimeOffset.UtcNow,
            DateTimeOffset.UtcNow,
            1.0,
            1.0,
            0,
            Array.Empty<TaskReassignmentRequestDto>(),
            Array.Empty<TaskStatusTimelineItemDto>(),
            Array.Empty<TaskChangeAuditItemDto>(),
            Array.Empty<TaskCapacityPointDto>());

    public static TaskDetailsDto FromRequest(UpsertTaskDto request, Guid? id = null) =>
        new(
            id ?? Guid.NewGuid(),
            request.Title,
            request.Description,
            request.AssignedMemberId,
            string.Empty,
            string.Empty,
            string.Empty,
            string.Empty,
            Guid.Empty,
            string.Empty,
            request.RequiredSpecialization,
            request.Priority,
            request.Complexity,
            request.EstimatedEffortHours,
            request.StartDate,
            request.DueDate,
            request.Status,
            0,
            false,
            null,
            DateTimeOffset.UtcNow,
            DateTimeOffset.UtcNow,
            1.0,
            1.0,
            0,
            Array.Empty<TaskReassignmentRequestDto>(),
            Array.Empty<TaskStatusTimelineItemDto>(),
            Array.Empty<TaskChangeAuditItemDto>(),
            Array.Empty<TaskCapacityPointDto>());
}
